language: node_js
node_js:
 - 'node'
 - '4'
install:
 - npm install
 - typings install
script:
 - npm run lint
 - npm run build
 - npm run cover

after_success:
 - 'nyc report --reporter=lcov > coverage.lcov && codecov'
